version: "3.3"

services:
    pgdump-s3:
        build:
            context: .
            dockerfile: pgdump-s3/Dockerfile
        image: leo/pgdump-s3:1.0.0
        environment:
            POSTGRESQL_URI : postgres://user:pass@host:port/dbname
            AWS_ACCESS_KEY_ID: ...
            AWS_SECRET_ACCESS_KEY: ...
            AWS_DEFAULT_REGION: us-west-1
            S3_BUCKET: ...
            DUMP_OBJECT_PREFIX: test_
            MAX_BACKUPS: 10
            BACKUP_CRON_SCHEDULE: 0 2 * * *
        restart: always    